import * as THREE from './vendor/three.module.js';
import {createCaravan} from './caravan.js?v=consistent-colours-1';
import {buildDesert,castleMaterials,buildCastle,animateDesert} from './desert-art.js';
import {generateCities,routeDistance,solve,distance} from './puzzle.js';
const $=id=>document.getElementById(id),names=['Start','Saffron','Sunwatch','Goldwell','Mirage','Dunestead','Qasr Bay','High Mesa','Copperwell','Sandstone','Windspire','Sunmarket','Dawnspire','Silkhaven'];
let cities=[],route=[0],answer=null,phase='planning',labels=[],towns=[],journey=0,showOptimal=true,sound=true,audioContext,timer;
const scene=new THREE.Scene();scene.background=new THREE.Color('#d9b982');scene.fog=new THREE.FogExp2('#d9b982',.009);
const camera=new THREE.OrthographicCamera(-20,20,15,-15,.1,180);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('world').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight('#c5dcff','#99744e',1.25));const sun=new THREE.DirectionalLight('#ffd199',3.7);sun.position.set(-22,17,-13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24});sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;sun.shadow.radius=3;scene.add(sun);
const island=new THREE.Group(),decor=new THREE.Group(),settlements=new THREE.Group(),paths=new THREE.Group();scene.add(island,decor,settlements,paths);
const mat=(color,opts={})=>new THREE.MeshStandardMaterial({color,roughness:1,...opts});const grass=mat('#dbb779'),sand=mat('#eacb91'),rock=mat('#b57e51'),trunk=mat('#715a40'),leaves=[mat('#a77549'),mat('#b68a52'),mat('#956641')],walls=[mat('#f2d6a1'),mat('#d8b782'),mat('#f0dfbb')],roofs=[mat('#b57048'),mat('#c48d59'),mat('#ba9566')],gold=new THREE.MeshBasicMaterial({color:'#9b361e',depthTest:false}),mint=new THREE.MeshBasicMaterial({color:'#075b73',depthTest:false});
function mesh(geo,material,parent,x=0,y=0,z=0){const o=new THREE.Mesh(geo,material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
const terrainMaterial=buildDesert(scene),castleMats=castleMaterials(terrainMaterial);
const caravan=createCaravan(scene);let travelElapsed=0,travelDistance=0,selectionStart=-99;
const selectionRing=mesh(new THREE.TorusGeometry(1,.045,8,64),new THREE.MeshBasicMaterial({color:'#ffe4a0',transparent:true,opacity:0,depthWrite:false}),scene);selectionRing.rotation.x=-Math.PI/2;selectionRing.castShadow=false;
function celebrateSelection(id){if(reduced)return;selectionStart=performance.now()/1000;selectionRing.position.set(cities[id].x,.69,cities[id].z);towns[id].userData.selectedAt=selectionStart;const line=paths.children.at(-1);if(line){line.userData.drawStart=selectionStart;line.geometry.setDrawRange(0,0);for(const arrow of line.children)arrow.visible=false;}}
function disposeGroup(group){while(group.children.length){const o=group.children.pop();o.parent=null;o.traverse(c=>{c.geometry?.dispose();if(c.userData.ownMaterial)c.material.dispose();});}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function chime(i=0){if(!sound)return;try{audioContext??=new AudioContext();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=261.63*2**([0,2,4,7,9][i%5]/12);g.gain.setValueAtTime(.06,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.7);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.7);}catch{}}
function select(id){if(phase!=='planning')return;if(route.length>1&&id===route.at(-1)){route.pop();update();return;}if(route.includes(id)){toast(id===0?'Your journey starts here.':`${names[id]} is already on your route.`);return;}route.push(id);chime(route.length);update();celebrateSelection(id);}
function newIsland(){caravan.reset();travelDistance=0;travelElapsed=0;selectionStart=-99;phase='planning';route=[0];answer=null;journey=0;showOptimal=true;$('result').hidden=true;$('optimal-legend').hidden=true;disposeGroup(decor);disposeGroup(settlements);$('labels').replaceChildren();labels=[];towns=[];cities=generateCities(Number($('difficulty').value));
 cities.forEach((c,i)=>{const g=new THREE.Group();g.position.set(c.x,.58,c.z);settlements.add(g);towns.push(g);buildCastle(g,i,castleMats);const ring=mesh(new THREE.TorusGeometry(1.02,.025,6,64),i===0?gold:leaves[2],g,0,.08);ring.rotation.x=-Math.PI/2;ring.castShadow=false;g.userData.ring=ring;const label=document.createElement('button');label.className='town-label';label.innerHTML=`<b>${i===0?'⌂':i}</b><span class="town-name">${names[i]}</span>`;label.setAttribute('aria-label',`${i===0?'Starting town':`Town ${i}`}: ${names[i]}`);label.onclick=()=>select(i);$('labels').appendChild(label);labels.push(label);});
 $('mapnote').textContent=`${cities.length-1} destinations are waiting for you`;$('instruction').textContent='Find the shortest route from Start through every other town exactly once. Click every town except the Start in the order you want to visit them, then choose Begin the journey. No return trip back to Start is allowed. Your goal is to travel to all the towns using the shortest possible travel distance. After you answer, the solution will be displayed.';update();}
function drawRoute(ids,material,y){for(let i=1;i<ids.length;i++){const a=cities[ids[i-1]],b=cities[ids[i]],points=[];for(let j=0;j<=20;j++){const t=j/20;points.push(new THREE.Vector3(a.x+(b.x-a.x)*t,y+Math.sin(t*Math.PI)*.25,a.z+(b.z-a.z)*t));}const line=mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),24,.065,6,false),material,paths);line.renderOrder=material===mint?12:11;line.castShadow=false;
 const length=Math.hypot(b.x-a.x,b.z-a.z),count=Math.max(1,Math.floor(length/3));
 for(let k=0;k<count;k++){const f=(k+1)/(count+1);const arrow=mesh(new THREE.ConeGeometry(.19,.52,3),material,line,a.x+(b.x-a.x)*f,y+Math.sin(f*Math.PI)*.25,a.z+(b.z-a.z)*f);arrow.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(b.x-a.x,0,b.z-a.z).normalize());arrow.renderOrder=line.renderOrder;arrow.castShadow=false;arrow.userData.fraction=f;}
 }}
function update(){const n=cities.length;$('stops').innerHTML=`${route.length-1} <small>/ ${n-1}</small>`;$('distance').innerHTML=`${Math.round(routeDistance(cities,route)*12)} <small>km</small>`;$('status').textContent=phase==='planning'?'PLANNING':phase==='travel'?'ON THE ROAD':'COMPLETE';$('submit').disabled=phase!=='planning'||route.length!==n;$('submit').innerHTML=phase==='travel'?'Journey in progress…':phase==='results'?'Journey complete ✓':route.length===n?'Begin the journey <span>→</span>':`Choose ${n-route.length} more town${n-route.length===1?'':'s'} <span>→</span>`;$('undo').disabled=route.length<2||phase!=='planning';$('clear').disabled=route.length<2||phase!=='planning';
 $('itinerary').replaceChildren();const order=[...route,...cities.map((_,i)=>i).filter(i=>!route.includes(i))];order.forEach(id=>{const b=document.createElement('button');b.className=`stop ${route.includes(id)?'selected':''} ${id===0?'home':''}`;b.textContent=id===0?'⌂':id;b.title=`${names[id]}${route.includes(id)?` · Stop ${route.indexOf(id)}`:''}`;b.setAttribute('aria-label',b.title);const canUndo=route.length>1&&id===route.at(-1);if(canUndo){b.title+=' · Click to undo';b.setAttribute('aria-label',b.title);}b.disabled=phase!=='planning'||(route.includes(id)&&!canUndo);b.onclick=()=>select(id);$('itinerary').appendChild(b);});
 labels.forEach((l,i)=>{l.classList.toggle('selected',route.includes(i));l.setAttribute('aria-pressed',String(route.includes(i)));towns[i].userData.ring.material=route.includes(i)?gold:leaves[2];});disposeGroup(paths);drawRoute(route,gold,.74);if(answer&&phase==='results'&&showOptimal)drawRoute(answer.route,mint,.89);}
function depart(){if(phase!=='planning'||route.length!==cities.length)return;answer=solve(cities);phase='travel';journey=0;travelDistance=0;travelElapsed=0;caravan.reset();$('instruction').textContent='Your merchant is on the road. Let’s see how far a little planning takes you.';update();}
function finish(){phase='results';chime(4);const yours=routeDistance(cities,route),score=Math.min(100,answer.length/yours*100),extra=Math.max(0,Math.round((yours-answer.length)*12));$('result').hidden=false;const perfect=Math.abs(yours-answer.length)<=1e-7*Math.max(1,answer.length);$('result').classList.toggle('perfect',perfect);$('result').innerHTML=`<div class="result-message"><span class="eyebrow">${perfect?'THE PERFECT JOURNEY':'JOURNEY COMPLETE'}</span><h2>${perfect?'Congratulations!':score>=95?'So close!':score>=80?'A good start!':'Try a shorter route!'}</h2><p>${perfect?'You found a shortest route. Beautifully planned.':'There’s a shorter way. Compare the routes and try again.'}</p></div><div class="result-score"><strong>${!perfect&&score>=99.95?'99.9':score.toFixed(1)}% <small>efficient</small></strong><p>Shortest: <b>${Math.round(answer.length*12)} km</b> · Extra: <b>${extra===0&&!perfect?'&lt;1':extra} km</b></p></div><div class="result-actions"><button id="compare">Hide shortest route</button><button id="retry">Try again ↻</button></div>`;$('compare').onclick=()=>{showOptimal=!showOptimal;$('compare').textContent=showOptimal?'Hide shortest route':'Show shortest route';$('optimal-legend').hidden=!showOptimal;update();};$('retry').onclick=newIsland;$('optimal-legend').hidden=false;$('instruction').textContent='Your journey is complete. Compare the terracotta route with the blue shortest path.';update();}
function resize(){const w=$('game').clientWidth,h=$('game').clientHeight;renderer.setSize(w,h);const mobile=w<620;const left=mobile?14:(w<=900?290:316),right=w-16,top=mobile?135:112,bottom=mobile?h-470:h-85;const availableWidth=right-left,availableHeight=Math.max(180,bottom-top);const scale=Math.min(availableWidth/31.5,availableHeight/19);const centerX=(left+right)/2-(mobile?0:Math.max(0,availableWidth-31.5*scale)*.38);camera.left=-w/(2*scale);camera.right=w/(2*scale);camera.top=h/(2*scale);camera.bottom=-h/(2*scale);camera.position.set(0,36,22);camera.lookAt(0,0,0);camera.setViewOffset(w,h,w/2-centerX,h/2-(top+bottom)/2,w,h);camera.updateProjectionMatrix();}
window.addEventListener('resize',resize);$('undo').onclick=()=>{if(phase==='planning'&&route.length>1){route.pop();update();}};$('clear').onclick=()=>{if(phase==='planning'){route=[0];update();}};$('submit').onclick=depart;$('new').onclick=newIsland;$('difficulty').onchange=newIsland;$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫ Sound on':'♫ Sound off';$('sound').setAttribute('aria-pressed',String(sound));chime(0);};window.addEventListener('keydown',e=>{if($('help-dialog').open||['SELECT','BUTTON'].includes(document.activeElement.tagName))return;if(e.key==='Backspace'){e.preventDefault();$('undo').click();}if(e.key==='Enter')depart();if(/^[1-9]$/.test(e.key)&&Number(e.key)<cities.length)select(Number(e.key));});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
renderer.domElement.addEventListener('pointerdown',event=>{if(phase!=='planning')return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(settlements.children,true)[0];if(hit){let object=hit.object;while(object.parent&&object.parent!==settlements)object=object.parent;const id=towns.indexOf(object);if(id>=0)select(id);}});
const projection=new THREE.Vector3();let last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function animate(time){requestAnimationFrame(animate);const dt=Math.min((time-last)/1000,.05);last=time;const t=time*.001;animateDesert(t,reduced);
 if(!reduced)settlements.traverse(o=>{if(o.userData.flag){const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(p.getX(i)*12+t*3)*.025);p.needsUpdate=true;const age=t-(o.parent.parent?.userData.selectedAt??-99);o.position.y=1.44+(age>=0&&age<.65?Math.sin(age/.65*Math.PI)*.16:0);}});
 const pulse=(t-selectionStart)/.65;selectionRing.visible=pulse>=0&&pulse<1&&!reduced;if(selectionRing.visible){selectionRing.scale.setScalar(.8+pulse*.85);selectionRing.material.opacity=(1-pulse)*.8;}
 for(const line of paths.children){if(line.userData.drawStart!==undefined){const progress=Math.min(1,(t-line.userData.drawStart)/.45);line.geometry.setDrawRange(0,Math.floor(progress*24)*36);for(const arrow of line.children)arrow.visible=progress>=arrow.userData.fraction;if(progress>=1)delete line.userData.drawStart;}}
 if(phase==='travel'){const total=routeDistance(cities,route);travelElapsed+=dt;const travelledTime=Math.min(travelElapsed,2.5)+Math.max(0,Math.min(travelElapsed-2.5,2))*2+Math.max(0,travelElapsed-4.5)*4;travelDistance=Math.min(total,total*(reduced?travelElapsed*2:travelledTime/14));if(travelDistance>=total)finish();}
 const moving=phase==='travel';caravan.update(cities,phase==='planning'?[0]:route,phase==='planning'?0:travelDistance,t,dt,moving,reduced);
 labels.forEach((l,i)=>{projection.set(cities[i].x,1.8,cities[i].z).project(camera);l.style.left=`${(projection.x*.5+.5)*$('game').clientWidth}px`;l.style.top=`${(-projection.y*.5+.5)*$('game').clientHeight}px`;l.style.zIndex=String(Math.round(100-projection.z*50));});renderer.render(scene,camera);}
newIsland();resize();requestAnimationFrame(animate);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'plan_merchant_route',description:'Select a complete route through the island towns, starting from town zero. Does not depart.',inputSchema:{type:'object',properties:{towns:{type:'array',items:{type:'integer'}}},required:['towns'],additionalProperties:false},execute(input){if(phase!=='planning')throw Error('Start a new attempt before planning.');const ids=input?.towns;if(!Array.isArray(ids)||ids.length!==cities.length-1||new Set(ids).size!==ids.length||ids.some(i=>!Number.isInteger(i)||i<1||i>=cities.length))throw Error('Include every town except zero exactly once.');route=[0,...ids];update();return {route,distanceKm:Math.round(routeDistance(cities,route)*12)};}})).catch(()=>{});}catch{}}
