/* Randomized Matematik 3 problem templates. Every template is constructed
   backwards from an integer coordinate and avoids product/quotient-rule work. */
((root)=>{
 'use strict';
 const int=(r,a,b)=>a+Math.floor(r()*(b-a+1)),pick=(r,a)=>a[int(r,0,a.length-1)],sign=r=>r()<.5?-1:1;
 const nonzero=(r,n=3)=>pick(r,Array.from({length:n*2},(_,i)=>i<n?i-n:i-n+1));
 const n=v=>`<mn>${v<0?'−'+Math.abs(v):v}</mn>`,v='<mi>t</mi>',op=s=>`<mo>${s}</mo>`,row=s=>`<mrow>${s}</mrow>`;
 const power=k=>k===1?v:`<msup>${v}${n(k)}</msup>`;
 const poly=terms=>{let text='';for(const [c,p] of terms){if(!c)continue;text+=(text?op(c<0?'−':'+'):c<0?op('−'):'')+(p===0||Math.abs(c)!==1?n(Math.abs(c)):'')+(p?power(p):'');}return row(text||n(0));};
 const math=s=>`<math display="block">${s}</math>`,fraction=(a,b)=>`<mfrac>${row(a)}${row(b)}</mfrac>`;
 const limit=(point,s)=>math(`<munder>${op('lim')}${row(v+op('→')+(point==='∞'?op('∞'):n(point)))}</munder>${op('(')}${s}${op(')')}`);
 const bound=x=>typeof x==='string'?x:n(x),integralExpr=(a,b,s)=>`<msubsup>${op('∫')}${bound(a)}${bound(b)}</msubsup>${op('(')}${s}${op(')')}<mspace width="0.2em"/><mi mathvariant="normal">d</mi>${v}`,integral=(a,b,s)=>math(integralExpr(a,b,s));
 const fn=(name,body)=>`<mi>${name}</mi>${op('(')}${v}${op(')')}${op('=')}${body}`,txt=x=>String(x).replace(/-/g,'−'),stack=(...lines)=>math(`<mtable>${lines.map(line=>`<mtr><mtd>${line}</mtd></mtr>`).join('')}</mtable>`);
 const ln=x=>row(`<mi mathvariant="normal">ln</mi>${op('(')}${n(x)}${op(')')}`),exp=exponent=>`<msup><mi>e</mi>${row(exponent)}</msup>`;
 const multiply=(coefficient,body)=>coefficient===1?body:coefficient===-1?op('−')+body:n(coefficient)+body;
 const signedTerm=(coefficient,body)=>!coefficient?'':op(coefficient<0?'−':'+')+(Math.abs(coefficient)===1?'':n(Math.abs(coefficient)))+body;

 function make(type,r=Math.random){
  let a,b,c,d,p,q,answer,html,solution,params,prompt,target,degree;
  switch(type){
  case 'pilot-limit':a=int(r,-3,3);b=int(r,-3,3);answer=a-b;prompt='Evaluate the limit.';html=limit(a,fraction(poly([[1,2],[-a-b,1],[a*b,0]]),poly([[1,1],[-a,0]])));solution=`Factor the numerator as (t − (${a}))(t − (${b})). Cancel t − (${a}). The limit is ${a} − (${b}) = ${answer}.`;params={a,b};break;
  case 'pilot-integral':a=nonzero(r);q=int(r,-3,3);b=q-a;answer=2*q;prompt='Evaluate the integral.';html=integral(0,2,poly([[a,1],[b,0]]));solution=`An antiderivative is (${a}/2)t² + (${b})t. Evaluating from 0 to 2 gives ${2*a} + (${2*b}) = ${answer}.`;params={a,b};break;
  case 'substitution':a=nonzero(r,2);p=int(r,-2,2);answer=int(r,-7,7);b=answer-a*p*p;prompt='Evaluate the limit.';html=limit(p,poly([[a,2],[b,0]]));solution=`Polynomials are continuous. Substitute t = ${p}: ${a}(${p})² + (${b}) = ${answer}.`;params={a,b,p};break;
  case 'derivative':a=nonzero(r,2);p=nonzero(r,2);answer=int(r,-7,7);b=answer-2*a*p;c=int(r,-3,3);prompt=`Evaluate f′(${txt(p)}).`;html=math(fn('f',poly([[a,2],[b,1],[c,0]])));solution=`f′(t) = (${2*a})t + (${b}). Therefore f′(${p}) = ${answer}.`;params={a,b,c,p};break;
  case 'quadratic-roots':p=int(r,-7,5);q=int(r,p+1,7);a=pick(r,[1,2]);b=-a*(p+q);c=a*p*q;d=pick(r,['smallest','largest']);answer=d==='smallest'?p:q;prompt=`Find the ${d} root.`;html=math(poly([[a,2],[b,1],[c,0]])+op('=')+n(0));solution=`Factor the left side as ${a}(t − (${p}))(t − (${q})). The roots are ${p} and ${q}, so the ${d} root is ${answer}.`;params={a,b,c,p,q,which:d};break;
  case 'cancel':a=int(r,-3,3);b=int(r,-3,3);answer=a+b;prompt='Evaluate the limit.';html=limit(a,fraction(poly([[1,2],[b-a,1],[-a*b,0]]),poly([[1,1],[-a,0]])));solution=`The numerator factors as (t − (${a}))(t + (${b})). Cancel the common factor. The limit is ${a} + (${b}) = ${answer}.`;params={a,b};break;
  case 'expand-product':a=int(r,-2,2);b=int(r,-2,2);p=int(r,-1,1);answer=2*p+a+b;prompt=`Evaluate f′(${txt(p)}).`;html=math(fn('f',op('(')+poly([[1,1],[a,0]])+op(')')+op('(')+poly([[1,1],[b,0]])+op(')')));solution=`First expand: f(t) = t² + (${a+b})t + (${a*b}). Then f′(t) = 2t + (${a+b}), so f′(${p}) = ${answer}.`;params={a,b,p};break;
  case 'affine-integral':a=nonzero(r);q=int(r,-3,3);b=q-a;answer=2*q;prompt='Evaluate the integral.';html=integral(0,2,poly([[a,1],[b,0]]));solution=`An antiderivative is (${a}/2)t² + (${b})t. The definite integral is ${answer}.`;params={a,b};break;
  case 'cubic-derivative':a=nonzero(r,2);b=int(r,-2,2);p=int(r,-1,1);answer=int(r,-7,7);c=answer-3*a*p*p-2*b*p;d=int(r,-3,3);prompt=`Evaluate f′(${txt(p)}).`;html=math(fn('f',poly([[a,3],[b,2],[c,1],[d,0]])));solution=`f′(t) = (${3*a})t² + (${2*b})t + (${c}). Substitution gives f′(${p}) = ${answer}.`;params={a,b,c,d,p};break;
  case 'quartic-integral':a=nonzero(r,2);b=int(r,-2,2);c=int(r,-2,2);answer=int(r,-7,7);d=answer-a-b-c;prompt='Evaluate the integral.';html=integral(0,1,poly([[4*a,3],[3*b,2],[2*c,1],[d,0]]));solution=`An antiderivative is (${a})t⁴ + (${b})t³ + (${c})t² + (${d})t. From 0 to 1 this is ${answer}.`;params={a,b,c,d};break;
  case 'second-derivative':a=nonzero(r,2);p=int(r,-1,1);answer=pick(r,[-6,-4,-2,0,2,4,6]);b=(answer-6*a*p)/2;c=int(r,-3,3);d=int(r,-3,3);prompt=`Evaluate f″(${txt(p)}).`;html=math(fn('f',poly([[a,3],[b,2],[c,1],[d,0]])));solution=`f″(t) = (${6*a})t + (${2*b}). Therefore f″(${p}) = ${answer}.`;params={a,b,c,d,p};break;
  case 'infinity':degree=pick(r,[2,3,4]);answer=nonzero(r,7);a=answer;b=int(r,-4,4);c=nonzero(r,4);prompt='Evaluate the limit.';html=limit('∞',fraction(poly([[a,degree],[b,0]]),poly([[1,degree],[c,0]])));solution=`The limit is the ratio of leading coefficients, ${a}/1 = ${answer}.`;params={a,b,c,degree};break;
  case 'maximum':p=int(r,-2,2);answer=int(r,-7,7);a=-1;b=2*p;c=answer-p*p;prompt='Find max g(t) on [−3, 3].';html=math(fn('g',poly([[a,2],[b,1],[c,0]])));solution=`The critical point is t = ${p}. Comparing it with both endpoints gives the maximum value ${answer}.`;params={a,b,c,p};break;
  case 'minimum':p=int(r,-2,2);answer=int(r,-7,7);a=1;b=-2*p;c=answer+p*p;prompt='Find min h(t) on [−3, 3].';html=math(fn('h',poly([[a,2],[b,1],[c,0]])));solution=`The critical point is t = ${p}. Comparing it with both endpoints gives the minimum value ${answer}.`;params={a,b,c,p};break;
  case 'tangent-parallel':answer=int(r,-3,3);a=nonzero(r,2);target=int(r,-5,5);b=target-2*a*answer;c=int(r,-4,4);d=int(r,-4,4);prompt='For which t is the tangent parallel to ℓ?';html=stack(fn('f',poly([[a,2],[b,1],[c,0]])),fn('ℓ',poly([[target,1],[d,0]])));solution=`The line has slope ${target}. Solve f′(t) = ${target}; this gives t = ${answer}.`;params={a,b,c,d,target};break;
  case 'integral-parameter':answer=int(r,-7,7);b=int(r,-3,3);target=2*answer+2*b;prompt='Find k.';html=math(integralExpr(0,2,row(`<mi>k</mi>${v}`+(b?op(b<0?'−':'+')+n(Math.abs(b)):'')))+op('=')+n(target));solution=`The integral equals 2k + (${2*b}). Solving 2k + (${2*b}) = ${target} gives k = ${answer}.`;params={k:answer,b,target};break;
  case 'exp-derivative':a=nonzero(r,4);answer=int(r,-7,7);b=answer-a;c=int(r,-4,4);prompt='Evaluate f′(0).';html=math(fn('f',row((a<0?op('−'):'')+(Math.abs(a)===1?'':n(Math.abs(a)))+exp(v)+(b?op(b<0?'−':'+')+n(Math.abs(b))+v:'')+(c?op(c<0?'−':'+')+n(Math.abs(c)):''))));solution=`f′(t) = (${a})eᵗ + (${b}). Since e⁰ = 1, f′(0) = ${answer}.`;params={a,b,c};break;
  case 'exp-integral':q=pick(r,[2,3]);a=nonzero(r,q===2?7:3);answer=a*(q-1);prompt='Evaluate the integral.';html=integral(0,ln(q),row((a<0?op('−'):'')+(Math.abs(a)===1?'':n(Math.abs(a)))+exp(v)));solution=`An antiderivative is (${a})eᵗ. Since e^(ln ${q}) = ${q}, the integral is ${answer}.`;params={a,n:q};break;
  case 'continuity':a=int(r,-3,3);b=int(r,-3,3);answer=a+b;prompt='Find k for continuity.';html=stack(fn('f',fraction(poly([[1,2],[b-a,1],[-a*b,0]]),poly([[1,1],[-a,0]])))+`<mspace width=".5em"/>${v}${op('≠')}${n(a)}`,`<mi>f</mi>${op('(')}${n(a)}${op(')')}${op('=')}<mi>k</mi>`);solution=`Cancel t − (${a}). The remaining expression tends to ${answer}, so k = ${answer}.`;params={a,b};break;
  case 'variable-integral':q=int(r,1,4);answer=nonzero(r,3);target=answer**3+q*answer;prompt='Find x.';html=math(integralExpr(0,'<mi>x</mi>',poly([[3,2],[q,0]]))+op('=')+n(target));solution=`The integral is x³ + (${q})x. This is strictly increasing, and x = ${answer} is the unique solution.`;params={q,target};break;
  case 'extremum-value':a=pick(r,[-1,1]);p=int(r,-2,2);answer=int(r,-7,7);prompt=`Find the only local ${a>0?'minimum':'maximum'} value.`;html=math(fn('f',poly([[a,4],[-4*a*p,3],[6*a*p*p,2],[-4*a*p**3,1],[a*p**4+answer,0]])));solution=`This is ${a>0?'':'−'}(t − (${p}))⁴ + (${answer}). Its only local ${a>0?'minimum':'maximum'} value is ${answer}.`;params={a,p,s:answer};break;
  case 'inflection-x':a=nonzero(r,2);answer=int(r,-3,3);q=int(r,-7,7);prompt='Find the inflection point’s t-coordinate.';html=math(fn('f',poly([[a,3],[-3*a*answer,2],[3*a*answer**2,1],[-a*answer**3+q,0]])));solution=`Set f″(t) = 0. This gives t = ${answer}.`;params={a,r:answer,s:q};break;
  case 'inflection-y':a=nonzero(r,2);p=int(r,-3,3);answer=int(r,-7,7);prompt='Find the inflection point’s y-coordinate.';html=math(fn('f',poly([[a,3],[-3*a*p,2],[3*a*p*p,1],[-a*p**3+answer,0]])));solution=`The inflection occurs at t = ${p}. Substitution gives y = ${answer}.`;params={a,r:p,s:answer};break;
  case 'tangent-intercept':a=nonzero(r,2);b=int(r,-4,4);p=int(r,-2,2);answer=int(r,-7,7);c=answer+a*p*p;prompt=`Find the tangent’s y-intercept at t = ${txt(p)}.`;html=math(fn('f',poly([[a,2],[b,1],[c,0]])));solution=`Use y = f′(${p})(t − (${p})) + f(${p}). Its y-intercept is ${answer}.`;params={a,b,c,p};break;
  case 'recover-value':a=int(r,-5,5);answer=int(r,-7,7);q=answer-a;p=int(r,1,4);prompt=`Find f(${p}).`;html=stack(`<mi>f</mi>${op('(')}${n(0)}${op(')')}${op('=')}${n(a)}`,integralExpr(0,p,`<msup><mi>f</mi><mo>′</mo></msup>${op('(')}${v}${op(')')}`)+op('=')+n(q));solution=`f(${p}) − f(0) = ${q}. Therefore f(${p}) = ${answer}.`;params={start:a,delta:q,p};break;
  case 'stationary-exp-value':a=nonzero(r,3);p=int(r,-2,2);answer=int(r,-7,7);c=answer-a+a*p;prompt='Find the stationary value.';html=math(fn('f',row((a<0?op('−'):'')+(Math.abs(a)===1?'':n(Math.abs(a)))+exp(v+(p?op(p<0?'+':'−')+n(Math.abs(p)):'') )+op(a<0?'+':'−')+n(Math.abs(a))+v+(c?op(c<0?'−':'+')+n(Math.abs(c)):''))));solution=`f′(t) = 0 only at t = ${p}. Substitution gives the stationary value ${answer}.`;params={a,p,c};break;
  case 'derivative-parameter':answer=int(r,-7,7);a=nonzero(r,2);p=pick(r,[-1,1]);b=int(r,-4,4);c=int(r,-3,3);target=3*a*p*p+2*answer*p+b;prompt='Find k.';html=stack(fn('f',row(poly([[a,3]])+op('+')+`<mi>k</mi>${power(2)}`+(b?op(b<0?'−':'+')+n(Math.abs(b))+v:'')+(c?op(c<0?'−':'+')+n(Math.abs(c)):''))),`<msup><mi>f</mi><mo>′</mo></msup>${op('(')}${n(p)}${op(')')}${op('=')}${n(target)}`);solution=`Differentiate, substitute t = ${p}, and solve the resulting linear equation. This gives k = ${answer}.`;params={k:answer,a,b,c,p,target};break;
  case 'exponential-equation':answer=nonzero(r,4);a=pick(r,[2,3]);b=-a*answer;prompt='Solve the equation.';html=math(`${exp(row(n(a)+v+op(b<0?'−':'+')+n(Math.abs(b))))}${op('=')}${n(1)}`);solution=`An exponential with base e equals 1 only when its exponent is 0. Solve ${a}t + (${b}) = 0; this gives t = ${answer}.`;params={a,b};break;
  case 'log-equation':answer=int(r,-5,7);q=int(r,1,4);a=answer-q;b=pick(r,[2,3]);target=b*q;prompt='Solve the equation.';html=math(`<mi mathvariant="normal">ln</mi>${op('(')}${v}${op(a<0?'+':'−')}${n(Math.abs(a))}${op(')')}${op('+')}<mi mathvariant="normal">ln</mi>${op('(')}${n(b)}${op(')')}${op('=')}<mi mathvariant="normal">ln</mi>${op('(')}${n(target)}${op(')')}`);solution=`Combine the logarithms: ln(${b}(t − (${a}))) = ln(${target}). Thus ${b}(t − (${a})) = ${target}, so t = ${answer}.`;params={a,b,target,q};break;
  case 'rational-equation':answer=int(r,-5,5);c=int(r,-4,4);if(c===answer)c+=c<4?1:-1;a=nonzero(r,3);target=nonzero(r,3);if(target===a)target=target===3?2:target+1;b=target*(answer-c)-a*answer;prompt='Solve the equation.';html=math(`${fraction(poly([[a,1],[b,0]]),poly([[1,1],[-c,0]]))}${op('=')}${n(target)}`);solution=`Multiply by t − (${c}) and solve the resulting linear equation. The solution is t = ${answer}.`;params={a,b,c,target};break;
  case 'rational-largest-root':p=int(r,-6,2);q=int(r,p+1,7);c=pick(r,Array.from({length:15},(_,i)=>i-7).filter(x=>x!==p&&x!==q));answer=q;prompt='Find the largest root.';html=math(`${fraction(poly([[1,2],[-p-q,1],[p*q,0]]),poly([[1,1],[-c,0]]))}${op('=')}${n(0)}`);solution=`The numerator factors as (t − (${p}))(t − (${q})). Its roots are ${p} and ${q}; the denominator excludes only t = ${c}. The largest root is ${answer}.`;params={p,q,c};break;
  case 'u-exp-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,fraction(row(exp(row(multiply(a,v)))+op('−')+n(1)),v));solution=`Use eᵘ = 1 + u + O(u²), with u = ${a===1?'t':a===-1?'−t':a+'t'}. Dividing by t gives the limit ${answer}.`;params={a};break;
  case 'u-sine-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,fraction(row(`<mi mathvariant="normal">sin</mi>${op('(')}${multiply(a,v)}${op(')')}`),v));solution=`Let u = ${a===1?'t':a===-1?'−t':a+'t'}. Then sin(u)/t = ${a}·sin(u)/u, so the standard sine limit gives ${answer}.`;params={a};break;
  case 'u-log-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,fraction(row(`<mi mathvariant="normal">ln</mi>${op('(')}${n(1)}${signedTerm(a,v)}${op(')')}`),v));solution=`Since ln(1 + u) = u + O(u²), substituting u = ${a===1?'t':a===-1?'−t':a+'t'} gives the limit ${answer}.`;params={a};break;
  case 'u-second-order-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,row(n(2*a)+fraction(row(exp(v)+op('−')+n(1)+op('−')+v),power(2))));solution=`The expansion eᵗ = 1 + t + t²/2 + O(t³) makes (eᵗ − 1 − t)/t² tend to 1/2. Multiplying by ${2*a} gives ${answer}.`;params={a};break;
  case 'u-parts-integral':a=nonzero(r,7);answer=a;prompt='Evaluate the integral.';html=integral(0,1,row(multiply(a,v)+exp(v)));solution=`Integration by parts gives ∫t eᵗdt = (t − 1)eᵗ. From 0 to 1 this equals 1, so the integral is ${a}·1 = ${answer}.`;params={a};break;
  case 'u-sub-integral':c=int(r,-3,3);answer=2*c+1;prompt='Evaluate the integral.';html=integral(0,1,row(n(4)+v+op('(')+power(2)+(c?op(c<0?'−':'+')+n(Math.abs(c)):'')+op(')')));solution=`Let u = t² + (${c}), so du = 2t dt. The integral becomes 2∫u du = u². Evaluating between t = 0 and t = 1 gives (${c+1})² − (${c})² = ${answer}.`;params={c};break;
  case 'u-trig-integral':a=nonzero(r,7);answer=a;prompt='Evaluate the integral.';html=integral(0,'<mfrac><mi>π</mi><mn>2</mn></mfrac>',row(n(2*a)+`<mi mathvariant="normal">sin</mi>${op('(')}${v}${op(')')}<mi mathvariant="normal">cos</mi>${op('(')}${v}${op(')')}`));solution=`Use u = sin t, du = cos t dt. The bounds become 0 and 1, giving ${2*a}∫₀¹u du = ${answer}.`;params={a};break;
  case 'u-improper-integral':a=nonzero(r,7);answer=a;prompt='Evaluate the integral.';html=integral(0,'<mo>∞</mo>',row(multiply(a,exp(row(op('−')+v)))));solution=`An antiderivative is −(${a})e^(−t). The exponential tends to 0 at infinity, so the improper integral equals ${answer}.`;params={a};break;
  case 'u-taylor-exp':a=nonzero(r,7);answer=a;prompt='Find the coefficient of t³ in the Maclaurin expansion.';html=math(fn('f',row(n(6*a)+exp(v))));solution=`The t³ coefficient of eᵗ is 1/3! = 1/6. Multiplying by ${6*a} gives coefficient ${answer}.`;params={a};break;
  case 'u-taylor-sine':a=nonzero(r,7);answer=a;prompt='Find the coefficient of t³ in the Maclaurin expansion.';html=math(fn('f',row(n(-6*a)+`<mi mathvariant="normal">sin</mi>${op('(')}${v}${op(')')}`)));solution=`sin t = t − t³/6 + O(t⁵). Multiplying by ${-6*a} makes the t³ coefficient ${answer}.`;params={a};break;
  case 'u-taylor-shift':a=nonzero(r,2);p=int(r,-2,2);answer=int(r,-7,7);b=answer-3*a*p;c=int(r,-3,3);d=int(r,-3,3);prompt=`Find the coefficient of (t − (${txt(p)}))² in the Taylor expansion about t = ${txt(p)}.`;html=math(fn('f',poly([[a,3],[b,2],[c,1],[d,0]])));solution=`The quadratic Taylor coefficient is f″(${p})/2. Here f″(t) = ${6*a}t + (${2*b}), so f″(${p})/2 = ${answer}.`;params={a,b,c,d,p};break;
  case 'u-implicit-circle':q=sign(r);answer=int(r,-7,7);p=-answer*q;target=p*p+q*q;prompt=`Find dy/dx at (${txt(p)}, ${txt(q)}).`;html=math(`<msup><mi>x</mi>${n(2)}</msup>${op('+')}<msup><mi>y</mi>${n(2)}</msup>${op('=')}${n(target)}`);solution=`Implicit differentiation gives 2x + 2y(dy/dx) = 0, hence dy/dx = −x/y. At (${p}, ${q}) this is ${answer}.`;params={p,q,target};break;
  case 'u-implicit-quadratic':q=sign(r);p=1;answer=nonzero(r,5);a=-answer*q;target=a+1;prompt=`Find dy/dx at (1, ${txt(q)}).`;html=math(`${multiply(a,'<msup><mi>x</mi>'+n(2)+'</msup>')}${op('+')}<msup><mi>y</mi>${n(2)}</msup>${op('=')}${n(target)}`);solution=`Differentiate implicitly: ${2*a}x + 2y(dy/dx) = 0. Thus dy/dx = −${a}x/y, which equals ${answer} at (1, ${q}).`;params={a,p,q,target};break;
  case 'u-separable-ode':a=nonzero(r,3);answer=2*a;prompt='Find y(ln 2).';html=stack(`<msup><mi>y</mi><mo>′</mo></msup>${op('=')}<mi>y</mi>`,`<mi>y</mi>${op('(')}${n(0)}${op(')')}${op('=')}${n(a)}`);solution=`Separate variables: dy/y = dt, so y = Ceᵗ. The initial condition gives C = ${a}; therefore y(ln 2) = ${a}·2 = ${answer}.`;params={a};break;
  case 'u-linear-ode':answer=int(r,-7,7);c=int(r,-4,4);b=2*answer-c;prompt='Find y(ln 2).';html=stack(`<msup><mi>y</mi><mo>′</mo></msup>${op('+')}<mi>y</mi>${op('=')}${n(c)}`,`<mi>y</mi>${op('(')}${n(0)}${op(')')}${op('=')}${n(b)}`);solution=`Using the integrating factor eᵗ gives y(t) = ${c} + (${b-c})e^(−t). Since e^(−ln 2) = 1/2, y(ln 2) = ${answer}.`;params={b,c};break;
  case 'u-oscillator-ode':answer=nonzero(r,7);a=-answer;prompt='Find y(π).';html=stack(`<msup><mi>y</mi><mo>″</mo></msup>${op('+')}<mi>y</mi>${op('=')}${n(0)}`,`<mi>y</mi>${op('(')}${n(0)}${op(')')}${op('=')}${n(a)}${op(',')}<mspace width=".4em"/><msup><mi>y</mi><mo>′</mo></msup>${op('(')}${n(0)}${op(')')}${op('=')}${n(0)}`);solution=`The solution is y(t) = ${a} cos t. Since cos π = −1, y(π) = ${answer}.`;params={a};break;
  case 'u-growth-ode':a=nonzero(r,3);answer=2*a;prompt='Find y(ln 2).';html=stack(`<msup><mi>y</mi><mo>″</mo></msup>${op('−')}<mi>y</mi>${op('=')}${n(0)}`,`<mi>y</mi>${op('(')}${n(0)}${op(')')}${op('=')}${n(a)}${op(',')}<mspace width=".4em"/><msup><mi>y</mi><mo>′</mo></msup>${op('(')}${n(0)}${op(')')}${op('=')}${n(a)}`);solution=`The characteristic roots are ±1. The initial conditions select y(t) = ${a}eᵗ, so y(ln 2) = ${answer}.`;params={a};break;
  case 'u-characteristic-root':p=int(r,-6,2);q=int(r,p+1,7);answer=q;prompt='Find the largest characteristic root.';html=math(`<msup><mi>y</mi><mo>″</mo></msup>${signedTerm(-(p+q),'<msup><mi>y</mi><mo>′</mo></msup>')}${signedTerm(p*q,'<mi>y</mi>')}${op('=')}${n(0)}`);solution=`The characteristic polynomial is r² − (${p+q})r + (${p*q}) = (r − (${p}))(r − (${q})). The largest root is ${answer}.`;params={p,q};break;
  case 'u-cosine-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,row(n(2*a)+fraction(row(n(1)+op('−')+`<mi mathvariant="normal">cos</mi>${op('(')}${v}${op(')')}`),power(2))));solution=`This is a 0/0 form. Applying L’Hôpital’s rule twice leaves ${2*a} cos t / 2, which tends to ${answer}.`;params={a};break;
  case 'u-taylor-third-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,row(n(6*a)+fraction(row(exp(v)+op('−')+n(1)+op('−')+v+op('−')+fraction(power(2),n(2))),power(3))));solution=`The first uncancelled term of eᵗ is t³/6. After division by t³ and multiplication by ${6*a}, the limit is ${answer}.`;params={a};break;
  case 'u-log-second-limit':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit(0,row(n(-2*a)+fraction(row(`<mi mathvariant="normal">ln</mi>${op('(')}${n(1)}${op('+')}${v}${op(')')}${op('−')}${v}`),power(2))));solution=`The expansion ln(1+t) = t − t²/2 + O(t³) makes the fraction tend to −1/2. Multiplication by ${-2*a} gives ${answer}.`;params={a};break;
  case 'u-radical-infinity':a=nonzero(r,7);answer=a;prompt='Evaluate the limit.';html=limit('∞',row(n(2*a)+v+op('(')+`<msqrt>${row(power(2)+op('+')+n(1))}</msqrt>`+op('−')+v+op(')')));solution=`Rationalize √(t²+1) − t. The expression becomes ${2*a}t/(√(t²+1)+t), whose limit is ${answer}.`;params={a};break;
  case 'u-partial-fractions-integral':a=nonzero(r,2);answer=int(r,-7,7);b=answer-2*a;prompt='Evaluate the integral.';html=integral(0,'<mo>∞</mo>',fraction(poly([[2*(a+b),2],[8*a+4*b,1],[8*a+2*b,0]]),row(`<msup>${row(op('(')+v+op('+')+n(1)+op(')'))}${n(2)}</msup><msup>${row(op('(')+v+op('+')+n(2)+op(')'))}${n(2)}</msup>`)));solution=`Decompose the integrand as ${2*a}/(t+1)² + (${2*b})/(t+2)². Integrating from 0 to ∞ gives ${2*a} + (${b}) = ${answer}.`;params={a,b};break;
  case 'u-implicit-hyperbola':p=sign(r);answer=nonzero(r,7);q=-answer*p;target=p*q;prompt=`Find dy/dx at (${txt(p)}, ${txt(q)}).`;html=math(`<mi>x</mi><mi>y</mi>${op('=')}${n(target)}`);solution=`Implicit differentiation gives y + x(dy/dx) = 0. Hence dy/dx = −y/x = ${answer} at the given point.`;params={p,q,target};break;
  case 'u-implicit-sine':a=nonzero(r,7);answer=-a;p=int(r,-2,2);target=a*p;prompt=`Find dy/dx at (${txt(p)}, 0).`;html=math(`${multiply(a,'<mi>x</mi>')}${op('+')}<mi mathvariant="normal">sin</mi>${op('(')}<mi>y</mi>${op(')')}${op('=')}${n(target)}`);solution=`Differentiate implicitly: ${a} + cos(y)(dy/dx) = 0. At y = 0, cos y = 1, so dy/dx = ${answer}.`;params={a,p,target};break;
  case 'u-cubic-maximum':a=nonzero(r,2);answer=int(r,-7,7);d=answer-2*Math.abs(a);prompt='Find the maximum value on [−2, 2].';html=math(fn('f',poly([[a,3],[-3*a,1],[d,0]])));solution=`The critical points are t = −1 and t = 1. Comparing them with both endpoints gives the maximum value ${answer}.`;params={a,d};break;
  case 'u-cubic-minimum':a=nonzero(r,2);answer=int(r,-7,7);d=answer+2*Math.abs(a);prompt='Find the minimum value on [−2, 2].';html=math(fn('f',poly([[a,3],[-3*a,1],[d,0]])));solution=`The critical points are t = −1 and t = 1. Comparing them with both endpoints gives the minimum value ${answer}.`;params={a,d};break;
  case 'u-rational-minimum':p=pick(r,[2,3]);answer=int(r,-7,7);c=answer-2*p;prompt='Find the minimum value on [1, 4].';html=math(fn('f',row(v+op('+')+fraction(n(p*p),v)+(c?signedTerm(c,''):''))));solution=`Differentiate to get f′(t) = 1 − ${p*p}/t². The positive critical point is t = ${p}; endpoint comparison confirms the minimum value ${answer}.`;params={p,c};break;
  default:throw Error('Unknown clue type');
  }
  if(!Number.isInteger(answer)||Math.abs(answer)>7)throw Error(`Invalid coordinate from ${type}`);
  return {type,prompt,html,answer,solution,params};
 }

 const briefing='Our spy obtained the following information about the enemy submarine.';
 const highSchoolMissions=[
  {name:'The first intercept',depth:120,zone:'SUNLIT REEF',level:'easy',message:briefing,types:['pilot-limit','pilot-integral','quadratic-roots','substitution','exponential-equation']},
  {name:'Silent running',depth:260,zone:'KELP PASSAGE',level:'easy',message:briefing,types:['quadratic-roots','cancel','affine-integral','expand-product','exponential-equation','rational-equation']},
  {name:'Crossed signals',depth:420,zone:'BLUE CHANNEL',level:'medium',message:briefing,types:['cubic-derivative','quartic-integral','second-derivative','maximum','minimum','log-equation','exponential-equation']},
  {name:'Pressure zone',depth:580,zone:'LOWER REEF',level:'medium',message:briefing,types:['tangent-parallel','integral-parameter','continuity','rational-equation','rational-largest-root','second-derivative']},
  {name:'Exponential wake',depth:740,zone:'TWILIGHT WATER',level:'medium',message:briefing,types:['exp-integral','infinity','quartic-integral','log-equation','exponential-equation','rational-equation','maximum','minimum']},
  {name:'Accumulated signal',depth:900,zone:'MIDNIGHT RIDGE',level:'hard',message:briefing,types:['variable-integral','tangent-intercept','recover-value','rational-largest-root','derivative-parameter']},
  {name:'Hidden turning point',depth:1040,zone:'ABYSSAL PLAIN',level:'hard',message:briefing,types:['extremum-value','inflection-x','inflection-y','stationary-exp-value','derivative-parameter','rational-largest-root']},
  {name:'The final transmission',depth:1180,zone:'DEEP DECODE',level:'hard',message:briefing,types:['variable-integral','tangent-intercept','inflection-x','inflection-y','stationary-exp-value','derivative-parameter','recover-value','rational-largest-root','log-equation']}
 ];
 const universityMissions=[
  {name:'Advanced contact',depth:180,zone:'ANALYSIS SHELF',level:'university',message:briefing,types:['u-exp-limit','u-sine-limit','u-cosine-limit','u-parts-integral','u-taylor-exp','u-implicit-circle']},
  {name:'Series current',depth:340,zone:'TAYLOR TRENCH',level:'university',message:briefing,types:['u-log-limit','u-taylor-third-limit','u-sub-integral','u-taylor-shift','u-separable-ode','u-implicit-hyperbola']},
  {name:'Implicit passage',depth:500,zone:'CURVED CHANNEL',level:'university',message:briefing,types:['u-second-order-limit','u-log-second-limit','u-trig-integral','u-implicit-circle','u-implicit-sine','u-linear-ode','u-cubic-maximum']},
  {name:'Improper waters',depth:660,zone:'INFINITE DROP',level:'university',message:briefing,types:['u-improper-integral','u-partial-fractions-integral','u-radical-infinity','u-characteristic-root','u-taylor-exp','u-implicit-quadratic']},
  {name:'Integrating factor',depth:820,zone:'VECTOR CURRENT',level:'university',message:briefing,types:['u-parts-integral','u-sub-integral','u-partial-fractions-integral','u-linear-ode','u-taylor-shift','u-second-order-limit','u-cubic-minimum']},
  {name:'Oscillation field',depth:980,zone:'HARMONIC BASIN',level:'university',message:briefing,types:['u-trig-integral','u-sine-limit','u-cosine-limit','u-oscillator-ode','u-taylor-sine','u-implicit-hyperbola','u-rational-minimum']},
  {name:'Exponential pressure',depth:1140,zone:'DYNAMIC ABYSS',level:'university',message:briefing,types:['u-exp-limit','u-log-second-limit','u-improper-integral','u-growth-ode','u-taylor-third-limit','u-implicit-sine','u-cubic-maximum']},
  {name:'Graduate transmission',depth:1320,zone:'UNIVERSITY DECODE',level:'university',message:briefing,types:['u-second-order-limit','u-cosine-limit','u-taylor-third-limit','u-radical-infinity','u-parts-integral','u-sub-integral','u-partial-fractions-integral','u-taylor-shift','u-implicit-circle','u-implicit-hyperbola','u-implicit-sine','u-separable-ode','u-linear-ode','u-oscillator-ode','u-growth-ode','u-characteristic-root','u-cubic-maximum','u-cubic-minimum','u-rational-minimum']}
 ];
 const missions=highSchoolMissions;
 const categories={
  'pilot-limit':'limit',substitution:'limit',cancel:'limit',infinity:'limit',continuity:'limit',
  'pilot-integral':'integral','affine-integral':'integral','quartic-integral':'integral','exp-integral':'integral','integral-parameter':'integral','variable-integral':'integral','recover-value':'integral',
  derivative:'derivative','expand-product':'derivative','cubic-derivative':'derivative','second-derivative':'derivative',maximum:'derivative',minimum:'derivative','tangent-parallel':'derivative','tangent-intercept':'derivative','extremum-value':'derivative','inflection-x':'derivative','inflection-y':'derivative','stationary-exp-value':'derivative','derivative-parameter':'derivative',
  'quadratic-roots':'equation','exponential-equation':'equation','log-equation':'equation','rational-equation':'equation','rational-largest-root':'equation'
  ,'u-exp-limit':'limit','u-sine-limit':'limit','u-log-limit':'limit','u-second-order-limit':'limit'
  ,'u-parts-integral':'integral','u-sub-integral':'integral','u-trig-integral':'integral','u-improper-integral':'integral'
  ,'u-taylor-exp':'taylor','u-taylor-sine':'taylor','u-taylor-shift':'taylor'
  ,'u-implicit-circle':'implicit','u-implicit-quadratic':'implicit'
  ,'u-separable-ode':'ode','u-linear-ode':'ode','u-oscillator-ode':'ode','u-growth-ode':'ode','u-characteristic-root':'ode'
  ,'u-cosine-limit':'limit','u-taylor-third-limit':'limit','u-log-second-limit':'limit','u-radical-infinity':'limit'
  ,'u-partial-fractions-integral':'integral'
  ,'u-implicit-hyperbola':'implicit','u-implicit-sine':'implicit'
  ,'u-cubic-maximum':'optimization','u-cubic-minimum':'optimization','u-rational-minimum':'optimization'
 };
 function missionsFor(level='high-school'){if(level==='high-school')return highSchoolMissions;if(level==='university')return universityMissions;throw Error('Invalid level');}
 function mission(index,r=Math.random,level='high-school'){const bank=missionsFor(level),m=bank[index];if(!m)throw Error('Invalid mission');const first=int(r,0,m.types.length-1),firstType=m.types[first],differentFamily=m.types.filter((type,i)=>i!==first&&categories[type]!==categories[firstType]),second=int(r,0,differentFamily.length-1),selected=[firstType,differentFamily[second]],clues=selected.map(type=>make(type,r));if(clues.some(c=>!Number.isInteger(c.answer)||Math.abs(c.answer)>7))throw Error('Target must be an integer grid point inside the outer grid border');return {...m,selectedTypes:selected,selectedCategories:selected.map(type=>categories[type]),clues};}
 function parse(text){const s=text.trim().replace(/−/g,'-').replace(',','.');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:\/[+-]?\d+)?$/.test(s))return null;const [a,b='1']=s.split('/'),value=Number(a)/Number(b);return Number(b)!==0&&Number.isFinite(value)&&Math.abs(value)<=7?value:null;}
 const api={make,mission,missions,highSchoolMissions,universityMissions,missionsFor,categories,parse};root.DeepMath=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
