(function(root){
  'use strict';
  const copy={
    en:{title:'The Calculus Millionaire',description:'A high-school and university calculus theory quiz with an escalating prize ladder.',brandSmall:'THE',brand:'CALCULUS MILLIONAIRE',introKicker:'A calculus theory challenge',introTitle:'Do you know the ideas behind the calculations?',introText:'Twelve questions build toward combined concepts and applications. Reach a checkpoint to secure your winnings—and use each lifeline only once.',start:'Take the hot seat →',introNote:'No time limit. No lengthy calculations.',finalAnswer:'Final answer',removeTwo:'Remove two',askClass:'Ask the class',vote:'Simulated vote',swap:'Swap',newQuestion:'New question',classVoted:'SIMULATED CLASS VOTE',prizeLadder:'PRIZE LADDER',best:'Best result',replayTitle:'Ready for another run?',replayText:'The questions and answer positions are randomized each time, so new questions can appear when you play again.',settings:'GAME SETTINGS',chooseLevel:'Choose a level',levelWarning:'Changing level starts a fresh game.',highSchool:'High school',university:'University',schoolDescription:'Swedish upper-secondary Matematik 3c',universityDescription:'Introductory applied single-variable calculus for engineering students',cancel:'Cancel',answers:'Answer choices',lifelines:'Lifelines',soundOn:'Sound on',soundOff:'Sound off',turnSoundOn:'Turn sound on',turnSoundOff:'Turn sound off',question:'QUESTION {n} OF {total}',forPrize:'FOR {prize}',confirm:'Is {letter} your final answer?',won:'€1,000,000 WON',correct:'CORRECT',incorrect:'THAT WAS NOT IT',winner:'You are the Calculus Millionaire!',secured:'{prize} reached',leave:'You leave with {prize}',replay:'Play again with new questions →',next:'Next question →',retry:'Try a new run'},
    sv:{title:'Analysmiljonären',description:'Ett teorispel i matematisk analys för gymnasiet och högskolan med en växande prisstege.',brandSmall:'SPELET',brand:'ANALYSMILJONÄREN',introKicker:'En teoriutmaning i matematisk analys',introTitle:'Förstår du idéerna bakom beräkningarna?',introText:'Tolv frågor leder fram till kombinerade begrepp och tillämpningar. Nå en säkerhetsnivå för att säkra din vinst – och använd varje livlina högst en gång.',start:'Ta plats i heta stolen →',introNote:'Ingen tidsgräns. Inga långa beräkningar.',finalAnswer:'Slutgiltigt svar',removeTwo:'Ta bort två',askClass:'Fråga klassen',vote:'Simulerad omröstning',swap:'Byt fråga',newQuestion:'En ny fråga',classVoted:'SIMULERAD KLASSOMRÖSTNING',prizeLadder:'PRISSTEGE',best:'Bästa resultat',replayTitle:'Redo för en ny omgång?',replayText:'Frågorna och svarens placering slumpas varje gång. Du kan därför få nya frågor när du spelar igen.',settings:'SPELINSTÄLLNINGAR',chooseLevel:'Välj nivå',levelWarning:'Om du byter nivå börjar en ny omgång.',highSchool:'Gymnasiet',university:'Högskola',schoolDescription:'Gymnasiets Matematik 3c',universityDescription:'Inledande tillämpad envariabelanalys för ingenjörsstudenter',cancel:'Avbryt',answers:'Svarsalternativ',lifelines:'Livlinor',soundOn:'Ljud på',soundOff:'Ljud av',turnSoundOn:'Slå på ljudet',turnSoundOff:'Stäng av ljudet',question:'FRÅGA {n} AV {total}',forPrize:'OM {prize}',confirm:'Är {letter} ditt slutgiltiga svar?',won:'DU VANN 1 000 000 €',correct:'RÄTT SVAR',incorrect:'DET VAR INTE RÄTT',winner:'Du är Analysmiljonären!',secured:'Du har nått {prize}',leave:'Du lämnar med {prize}',replay:'Spela igen med nya frågor →',next:'Nästa fråga →',retry:'Försök igen'}
  };
  const staticText={'.show-brand>div>span':'brandSmall','.show-brand strong':'brand','#intro .kicker':'introKicker','#intro-title':'introTitle','#intro>p:not(.kicker)':'introText','#start':'start','#intro>small':'introNote','#final-answer':'finalAnswer','#fifty small':'removeTwo','#audience>span':'askClass','#audience small':'vote','#swap>span':'swap','#swap small':'newQuestion','#audience-panel>strong':'classVoted','.ladder-title':'prizeLadder','#best-label':'best','#replay-note strong':'replayTitle','#replay-note span':'replayText','#level-dialog .kicker':'settings','#level-title':'chooseLevel','#level-dialog>p:not(.kicker)':'levelWarning','#level-high-school strong':'highSchool','#level-high-school span':'schoolDescription','#level-university strong':'university','#level-university span':'universityDescription','#cancel-level':'cancel'};
  function t(lang,key,values={}){return copy[lang][key].replace(/\{(\w+)\}/g,(_,name)=>values[name]??'');}
  function apply(lang){
    document.documentElement.lang=lang;document.title=t(lang,'title');
    document.querySelector('meta[name="description"]').content=t(lang,'description');
    Object.entries(staticText).forEach(([selector,key])=>document.querySelector(selector).textContent=t(lang,key));
    document.getElementById('answers').setAttribute('aria-label',t(lang,'answers'));
    document.querySelector('.lifelines').setAttribute('aria-label',t(lang,'lifelines'));
    document.querySelector('.ladder-panel').setAttribute('aria-label',t(lang,'prizeLadder'));
    document.getElementById('language').value=lang;
  }
  root.CalculusMillionaireI18n={copy,t,apply};
})(globalThis);
