 'use strict';
(()=>{
const $=id=>document.getElementById(id),M=DeepMath;
let index=0,mission,shots=[],phase='ready',won=false,firstShotWins=0,frame=0,timer=0,aim=null,level='high-school',missionSet=M.missionsFor(level);
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let motion=!reduced.matches;
const GRID_LIMIT=8,STEP=22.5,px=x=>300+STEP*x,py=y=>240-STEP*y;
let audioContext;
function sound(name){const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return;try{audioContext=audioContext||new AudioEngine();if(audioContext.state==='suspended')audioContext.resume();const sounds={aim:[[540,690,.08,.025,'sine',0]],launch:[[150,520,.45,.045,'sawtooth',0],[90,210,.5,.035,'sine',.04]],hit:[[170,65,.55,.09,'sawtooth',0],[420,880,.38,.05,'sine',.08],[660,990,.3,.035,'sine',.16]],miss:[[260,105,.5,.045,'triangle',0],[190,80,.42,.03,'sine',.12]]};const now=audioContext.currentTime;for(const [from,to,duration,volume,type,delay] of sounds[name]||[]){const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),start=now+delay,end=start+duration;oscillator.type=type;oscillator.frequency.setValueAtTime(from,start);oscillator.frequency.exponentialRampToValueAtTime(to,end);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.015);gain.gain.exponentialRampToValueAtTime(.0001,end);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(start);oscillator.stop(end+.02);}}catch{}}
reduced.addEventListener('change',e=>{motion=!e.matches});
$('chart').addEventListener('click',e=>{
 if(phase!=='ready')return;
 const svg=$('chart').querySelector('svg'),matrix=svg.getScreenCTM();if(!matrix)return;
 const cursor=svg.createSVGPoint();cursor.x=e.clientX;cursor.y=e.clientY;
 const local=cursor.matrixTransform(matrix.inverse()),x=(local.x-300)/STEP,y=(240-local.y)/STEP;
 if(x < -GRID_LIMIT-.5 || x > GRID_LIMIT+.5 || y < -GRID_LIMIT-.5 || y > GRID_LIMIT+.5)return;
 aim={x:Math.max(-GRID_LIMIT,Math.min(GRID_LIMIT,Math.round(x))),y:Math.max(-GRID_LIMIT,Math.min(GRID_LIMIT,Math.round(y)))};sound('aim');validate();
 $('feedback').textContent=`Aim set to (${aim.x}, ${aim.y}). Launch when you’re ready.`;
});
$('marine-life').innerHTML=Array.from({length:7},(_,i)=>`<img class="fish ${i%2?'reverse':''}" src="fish.png" alt="" style="--top:${12+i*10}%;--duration:${22+i*4}s;--delay:-${i*9+8}s;width:${45+(i%3)*17}px;opacity:${.35+(i%3)*.18}">`).join('');
$('bubbles').innerHTML=Array.from({length:17},(_,i)=>`<i class="bubble" style="--left:${(i*37)%100}%;--size:${3+i%6}px;--duration:${7+i%7}s;--delay:-${i*.9}s"></i>`).join('');
function point(x,y){const r=$('porthole'),w=r.clientWidth,h=r.clientHeight,narrow=window.innerWidth<=760,vw=narrow?450:600,left=narrow?75:0,s=Math.min(w/vw,h/480);return{x:(w-vw*s)/2+(px(x)-left)*s,y:(h-480*s)/2+py(y)*s};}
function positionSub(){if($('target-sub').hidden)return;const p=point(mission.clues[0].answer,mission.clues[1].answer);$('target-sub').style.left=p.x+'px';$('target-sub').style.top=p.y+'px';}
window.addEventListener('resize',()=>{chart();positionSub()});
function chart(){let svg='<svg viewBox="'+(window.innerWidth<=760?'75 0 450 480':'0 0 600 480')+'" role="img" aria-labelledby="grid-title"><title id="grid-title">Underwater Cartesian search grid</title><rect x="112" y="52" width="376" height="376" rx="9" fill="#021c2b" opacity=".34"/>';
for(let i=-GRID_LIMIT;i<=GRID_LIMIT;i++){svg+=`<path d="M ${px(i)} 60 V 420 M 120 ${py(i)} H 480" stroke="${i===0?'#c1fbe9':'#b2ebdf'}" stroke-opacity="${i===0?.8:.23}" stroke-width="${i===0?1.4:.6}"/>`;if(i!==0)svg+=`<text x="${px(i)}" y="${py(0)+16}" text-anchor="middle" fill="#e1fff7" font-size="12" paint-order="stroke" stroke="#083447" stroke-width="3">${i}</text><text x="${px(0)-8}" y="${py(i)+4}" text-anchor="end" fill="#e1fff7" font-size="12" paint-order="stroke" stroke="#083447" stroke-width="3">${i}</text>`;}
svg+='<text x="493" y="244" fill="#b1fce1" font-size="15">x</text><text x="296" y="45" fill="#b1fce1" font-size="15">y</text>';
for(const s of shots){if(!s.resolved)continue;svg+=s.hit?`<circle cx="${px(s.x)}" cy="${py(s.y)}" r="13" fill="none" stroke="#ffe1a0" stroke-width="2"/>`:`<path d="M ${px(s.x)-5} ${py(s.y)-5} l10 10 m-10 0 l10 -10" stroke="#ffb69c" stroke-width="2.5"/>`;}
if(phase==='ready'&&aim)svg+=`<circle cx="${px(aim.x)}" cy="${py(aim.y)}" r="10" fill="none" stroke="#ffda86" stroke-width="1.8"/><path d="M ${px(aim.x)-16} ${py(aim.y)} h32 M ${px(aim.x)} ${py(aim.y)-16} v32" stroke="#ffda86"/>`;
if(phase==='finished')svg+=`<circle cx="${px(mission.clues[0].answer)}" cy="${py(mission.clues[1].answer)}" r="19" fill="none" stroke="#83f3cf" stroke-width="2" stroke-dasharray="4 4"/>`;
$('chart').innerHTML=svg+'</svg>';
let summary=phase==='finished'?`Target: (${mission.clues[0].answer}, ${mission.clues[1].answer}) · ${won?'sunk':'revealed'}`:aim?'':'Click the grid to set your aim.';
if(shots.some(s=>s.resolved))summary+=' · '+shots.filter(s=>s.resolved).map(s=>`(${s.x}, ${s.y}) ${s.hit?'hit':'miss'}`).join(' / ');$('chart-description').textContent=summary;
}
function validate(){$('launch').disabled=phase!=='ready'||!aim;chart();return phase==='ready'&&!!aim;}
function loadMission(focus=false){cancelAnimationFrame(frame);clearTimeout(timer);$('result').close();phase='ready';shots=[];won=false;mission=M.mission(index,Math.random,level);$('target-sub').hidden=true;$('target-sub').classList.remove('sinking');$('effects').getContext('2d').clearRect(0,0,$('effects').width,$('effects').height);
$('mission-counter').textContent=`MISSION ${String(index+1).padStart(2,'0')} / ${String(missionSet.length).padStart(2,'0')}`;$('mission-name').textContent=mission.name;$('zone').textContent=mission.zone;$('depth').textContent=mission.depth;$('briefing').textContent=mission.message;$('progress').innerHTML=missionSet.map((m,i)=>`<li class="${i<index?'done':i===index?'current':''}" aria-label="Mission ${i+1}: ${i<index?'complete':i===index?'current':'upcoming'}"></li>`).join('');
$('clues').innerHTML=mission.clues.map((c,i)=>`<article class="clue"><div class="clue-top"><span class="clue-axis">${i?'Y':'X'} COORDINATE</span></div><p>${c.prompt}</p>${c.html}</article>`).join('');aim=null;$('shots').textContent='2 torpedoes ready';$('ammo-icons').textContent='▰ ▰';$('launch').innerHTML='Launch torpedo <span>↗</span>';$('feedback').textContent=index===0?'Decode both intercepts.':'Fresh intercepts received. Solve both clues before you launch.';validate();if(focus)$('chart').focus();}
function animateShot(shot,done){if(!motion){done();return;}const canvas=$('effects'),w=$('porthole').clientWidth,h=$('porthole').clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const dest=point(shot.x,shot.y),start={x:w*.5,y:h+20},time=performance.now();
function tick(now){const elapsed=now-time,t=Math.min(elapsed/1050,1);ctx.clearRect(0,0,w,h);if(t<1){const x=start.x+(dest.x-start.x)*t,y=start.y+(dest.y-start.y)*t;const trail=ctx.createLinearGradient(start.x,start.y,x,y);trail.addColorStop(0,'#affff000');trail.addColorStop(1,'#e5fffccc');ctx.strokeStyle=trail;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle='#ffdc95';ctx.shadowColor='#91ffe2';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}else{const impact=(elapsed-1050)/650;for(let i=0;i<3;i++){ctx.strokeStyle=shot.hit?`rgba(255,219,139,${Math.max(0,1-impact)})`:`rgba(160,234,246,${Math.max(0,1-impact)})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(dest.x,dest.y,3+impact*(30+i*15),0,Math.PI*2);ctx.stroke();}}if(elapsed<1700&&motion){frame=requestAnimationFrame(tick);}else{ctx.clearRect(0,0,w,h);done();}}frame=requestAnimationFrame(tick);}
function launch(){if(phase!=='ready'||!validate())return;sound('launch');const shot={...aim,hit:aim.x===mission.clues[0].answer&&aim.y===mission.clues[1].answer,resolved:false};shots.push(shot);phase='firing';$('porthole').scrollIntoView({behavior:motion?'smooth':'instant',block:'center'});$('launch').textContent='Torpedo away…';$('feedback').textContent='Torpedo away. Holding position…';$('shots').textContent=`${2-shots.length} torpedo${shots.length===1?'':'es'} remaining`;$('ammo-icons').textContent=shots.length===1?'▰ ▱':'▱ ▱';validate();animateShot(shot,()=>resolveShot(shot));}
function resolveShot(shot){shot.resolved=true;won=shot.hit;sound(won?'hit':'miss');if(won||shots.length===2){phase='finished';if(won&&shots.length===1)firstShotWins++;$('feedback').textContent=won?'Direct hit. Submarine going down! Agent Ink sends eight thumbs up.':'The target slipped away. Let’s decode that transmission together.';$('target-sub').hidden=false;positionSub();if(won&&motion)$('target-sub').classList.add('sinking');$('launch').textContent=won?'Target neutralized':'Mission ended';validate();timer=setTimeout(showResult,won&&motion?1900:250);}else{phase='ready';aim=null;$('feedback').textContent='That seaweed will never bother us again. One torpedo left — check both calculations, then choose another point.';$('launch').innerHTML='Launch torpedo <span>↗</span>';validate();}}
function showResult(){if(phase!=='finished'||$('result').open)return;const final=won&&index===missionSet.length-1,total=missionSet.length;$('result-tag').textContent=final?'OPERATION COMPLETE':won?'TARGET NEUTRALIZED':'MISSION RESULT';$('result-title').textContent=final?'All clear, captain.':won?'A beautifully calculated hit.':'A small leak in the detective work…';$('result-copy').textContent=final?`${total} submarines found. ${firstShotWins} of ${total} missions cleared on the first shot of the successful attempt. Agent Ink is taking a very long holiday.`:won?`Mission ${index+1} complete. ${index<total-1?'Next: '+missionSet[index+1].name+'.':''}`:'Two shots, no match. Here are the decoded coordinates before you try again.';$('success-art').hidden=!won;$('solutions').hidden=won;if(!won)$('solutions').innerHTML=mission.clues.map((c,i)=>`<h3>${i?'Y':'X'} coordinate = ${c.answer}</h3><p>${c.solution}</p>`).join('')+`<p>Target coordinates: <strong>(${mission.clues[0].answer}, ${mission.clues[1].answer})</strong>.</p>`;$('continue').textContent=final?'New expedition ↻':won?'Next mission →':index===0?'Retry pilot mission ↻':'Retry with new clues ↻';$('result').showModal();}
function chooseLevel(next){$('level-dialog').close();if(next===level)return;level=next;missionSet=M.missionsFor(level);index=0;firstShotWins=0;$('level-name').textContent=level==='university'?'University':'High school';$('level-high-school').setAttribute('aria-pressed',String(level==='high-school'));$('level-university').setAttribute('aria-pressed',String(level==='university'));loadMission(true);}
$('settings').onclick=()=>$('level-dialog').showModal();$('cancel-settings').onclick=()=>$('level-dialog').close();$('level-dialog').addEventListener('cancel',e=>{e.preventDefault();$('level-dialog').close()});$('level-high-school').onclick=()=>chooseLevel('high-school');$('level-university').onclick=()=>chooseLevel('university');
$('launch').addEventListener('click',launch);$('continue').onclick=()=>{if(phase!=='finished')return;if(won){index++;if(index===missionSet.length){index=0;firstShotWins=0;}}loadMission(true);};loadMission();
})();
